# Generated by Django 4.2.2 on 2024-02-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('identificacion', models.CharField(max_length=10, verbose_name='Identificación')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Foto de perfil')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('registro', 'Registro Civil'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('identificacion', models.CharField(max_length=10, verbose_name='Identificación')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Administradores',
                'ordering': ['-nombres'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('registro', 'Registro Civil'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('identificacion', models.CharField(max_length=10, verbose_name='Identificación')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['-nombres'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula'), ('registro', 'Registro Civil'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('identificacion', models.CharField(max_length=10, verbose_name='Identificación')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-nombres'],
            },
        ),
    ]
